[package]
name = "rust-launcher"
version.workspace = true
edition = "2021"

[dependencies]
mozdevice = "0.5"
frida.workspace = true
common_utils = { path = "../common" }
anyhow.workspace = true
base64.workspace = true
