[alias]
    xtask = "run --package xtask --"
    rr    = "run --release"
    r     = "run"
    br    = "build --release"
    b     = "build"
    rb    = "run --bin"
    rrb   = "run --release --bin"
